### ISSUE TITLE
note error for 1 million max character limit for texts

### ISSUE THREAD

**Issue by poldham** [quanteda/spacyr#108]
Hi Ken and collaborators, 

Many thanks for the package. This is just a note that spacy_parse() will fail if a text in a readtext object is over 1 million characters. The solution in those cases seems to be to count nchar in the table and then filter to those texts lower than 1 million. That has worked for me so far but I haven't tried individual large texts yet (I am assuming that splitting will work).  message is below. 

Thanks again for the package!

Best, 

Paul

The message:

Error in py_run_string_impl(code, local, convert) : 
  ValueError: [E088] Text of length 1071747 exceeds maximum of 1000000. The v2.x parser and NER models require roughly 1GB of temporary memory per 100,000 characters in the input. This means long texts may cause memory allocation errors. If you're not using the parser or NER, it's probably safe to increase the `nlp.max_length` limit. The limit is in number of characters, so you can check whether your inputs are too long by checking `len(text)`.

**Comment by amatsuo** [comment]
Hello @poldham 

Thank you for the feedback. Yes. We are aware of this limitation. The choice for us is whether to check the object size before sending the text to python. Checking it in R does not make much difference except for showing a bit nicer error message. 

However, the bottleneck to do so seems not too big even if a fairly large number of texts are checked.
```r
> microbenchmark::microbenchmark(tmp %>% nchar %>% max, times = 10)
Unit: milliseconds
                  expr      min       lq     mean   median       uq      max neval
 tmp %>% nchar %>% max 761.8987 778.4443 843.0344 787.4298 808.1892 1347.083    10
```
`tmp` is a text vector of 2.6M tweets, and I ran it on my laptop.

Probably we will include it in the next update.
