### ISSUE TITLE
Problems installing spacyr

### ISSUE THREAD

**Issue by JuanRivas1109** [quanteda/spacyr#127]
After having performed the link procedure (https://github.com/quanteda/spacyr). I could not install the package in r, since it gives me the following error:

Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools

You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
Error: Error 1 occurred installing packages into conda environment spacy_condaenv
In addition: Warning message:
running command '"C:/Users/Juancho/MINICO~2/Scripts/activate" spacy_condaenv && pip install --upgrade --ignore-installed "spacy"' had status 1 

spacy_initialize()
Found 'spacy_condaenv'. spacyr will use this environment
Error in py_run_file_impl(file, local, convert) : 
  ModuleNotFoundError: No module named 'spacy'

**Comment by kbenoit** [comment]
Have you followed the instructions and installed Microsoft Visual C++ 14.0?

**Comment by amatsuo** [comment]
It seems that installation of spacy in python is failing. I would try to do it directly in python. 

First activate the environment. In command line:
```bash
activate spacy_condaenv
```

Then install spacy
```python
pip install spacy
```
This installation would probably fail, but error messages will help to understand why you cannot install.

**Comment by methodds** [comment]
For me the same error message appears on my windows machine, but spacy is definitely installed (in the correct environment).
