### ISSUE TITLE
Error in initialize_python(required_module, use_environment)

### ISSUE THREAD

**Issue by shahronak47** [quanteda/spacyr#128]
I am trying to use `spacyr`. I installed it using 

    install.packages("spacyr")

it installed correctly without any error. Then loaded the library using 

    library(spacyr)

This works too without any errors, but when I do 

    spacy_initialize()

I get, 

>Python space is already attached.  If you want to switch to a different Python, please restart R.
Error in initialize_python(required_module, use_environment) : 
  Your current architecture is 64bit however this version of Python is compiled for 32bit.

I also tried the example given , 

    txt <- c(d1 = "spaCy excels at large-scale information extraction tasks.",
         d2 = "Mr. Smith goes to North Carolina.")
    # process documents and obtain a data.table
    parsedtxt <- spacy_parse(txt)
It gives me the same error. 

This is my `sessionInfo` if that is of any help. 

    sessionInfo()
    #R version 3.4.4 (2018-03-15)
    #Platform: x86_64-w64-mingw32/x64 (64-bit)
    #Running under: Windows >= 8 x64 (build 9200)

     #Matrix products: default

    #locale:
    #[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
    #[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

    #attached base packages:
    #[1] stats     graphics  grDevices utils     datasets  methods   base     

    #other attached packages:
    #[1] spacyr_0.9.91     data.table_1.11.4

    #loaded via a namespace (and not attached):
    #[1] Rcpp_0.12.16    lattice_0.20-35 digest_0.6.15   withr_2.1.2     grid_3.4.4      R6_2.2.2        jsonlite_1.5    git2r_0.21.0   
     #[9] httr_1.3.1      curl_3.2        Matrix_1.2-12   reticulate_1.10 devtools_1.13.5 tools_3.4.4     yaml_2.1.18     compiler_3.4.4 
    #[17] memoise_1.1.0  

What can I do to resolve it?

**Comment by amatsuo** [comment]
Sorry for a very slow response, but I think the obvious solution is to install a python for 64-bit. If you still have some issues, please reopen this issue.
