### ISSUE TITLE
No connection to a Python backend in Kaggle Kernels environment

### ISSUE THREAD

**Issue by prokopyev** [quanteda/spacyr#131]
Colleagues,

Both CRAN and GitHub versions of `spacyr` fail to connect to Python backend in Kaggle Kernels environment.

```
library(spacyr)
spacy_install()
No conda was found in the system. 
Error in utils::menu(c("No", "Yes"), title = "Do you want spacyr to download miniconda in ~/miniconda?"): menu() cannot be used non-interactively
Traceback:

1. spacy_install()
2. utils::menu(c("No", "Yes"), title = "Do you want spacyr to download miniconda in ~/miniconda?")
3. stop("menu() cannot be used non-interactively")

```

Reprex: https://www.kaggle.com/prokopyev/spacyr-installation?scriptVersionId=6426272

The R Kaggle Kernels environment comes with the following Python backend (they've built it for R-Keras):

```
library(reticulate)
py_config()
py_discover_config()

python:         /root/.virtualenvs/r-tensorflow/bin/python
libpython:      /usr/lib/python2.7/config-x86_64-linux-gnu/libpython2.7.so
pythonhome:     /usr:/usr
virtualenv:     /root/.virtualenvs/r-tensorflow/bin/activate_this.py
version:        2.7.13 (default, Sep 26 2018, 18:42:22)  [GCC 6.3.0 20170516]
numpy:          /root/.virtualenvs/r-tensorflow/local/lib/python2.7/site-packages/numpy
numpy_version:  1.15.2
```

If I try to point to it:

```
spacy_initialize(python_executable = "/root/.virtualenvs/r-tensorflow/bin/python")

Error in set_spacy_python_option(python_executable, virtualenv, condaenv, : spaCy or language model en is not installed in /root/.virtualenvs/r-tensorflow/bin/python
Traceback:

1. spacy_initialize(python_executable = "/root/.virtualenvs/r-tensorflow/bin/python")
2. set_spacy_python_option(python_executable, virtualenv, condaenv, 
 .     check_env, refresh_settings, ask, model)
3. stop("spaCy or language model ", model, " is not installed in ", 
 .     python_executable)
```

Do you know what can be done on your side, and what should I ask Kaggle to change to make spacyr work on Kaggle?

**Comment by prokopyev** [comment]
The comments from Kaggle team clarify that their Docker image for R can be updated. 

To make Kaggle support spacyr, `spacyr::spacy_install()` function needs to work more like that of `keras::install_keras()`, i.e. without interactive command line prompts. Can this be adjusted?

**Comment by amatsuo** [comment]
It seems that `conda` cannot be detected automatically in your environment. 

For finding `conda`, we use `reticulate::conda_binary()`. The default value of the argument `conda` is `"auto"` and I believe that in your environment, `reticulate::conda_binary(conda = "auto")` will return `NULL`.

Can you try with specific path to conda? e.g. `spacy_install(conda = "/my/path/to/conda")`

**Comment by amatsuo** [comment]
Regarding @prokopyev's comments, the specific line which causes the err (the line with `utils::menu()`) was executed only when `conda` cannot be found on the path and it should be avoidable on Kaggle. 

`spacy_install()` is called when we deploy it on travis (which is not interactive) and has never caused the issue.

**Comment by prokopyev** [comment]
Thanks for a suggestions.

> Can you try with specific path to conda? e.g. `spacy_install(conda = "/my/path/to/conda")`

It seems Kaggle Kernels R Docker image does not have conda:

```
$ reticulate::conda_binary() 
Error: Unable to find conda binary. Is Anaconda installed?
Traceback:

1. reticulate::conda_binary()
2. stop("Unable to find conda binary. Is Anaconda installed?", call. = FALSE)
```

I did try to point it to Python that they have installed for r-keras:

```
spacy_initialize(python_executable = "/root/.virtualenvs/r-tensorflow/bin/python")

Error in set_spacy_python_option(python_executable, virtualenv, condaenv, : spaCy or language model en is not installed in /root/.virtualenvs/r-tensorflow/bin/python
Traceback:

1. spacy_initialize(python_executable = "/root/.virtualenvs/r-tensorflow/bin/python")
2. set_spacy_python_option(python_executable, virtualenv, condaenv, 
 .     check_env, refresh_settings, ask, model)
3. stop("spaCy or language model ", model, " is not installed in ", 
 .     python_executable)

```

Do you think the matter might be solved with a pip install of spacy and its lang models in Kaggle's docker image: https://github.com/Kaggle/docker-rstats/blob/master/Dockerfile ?

**Comment by amatsuo** [comment]
Okay. In that case, it might be worth trying to install it through `spacy_install_virtualenv()` instead. 

For the arguments:

- you may need to specify `python_path` if the default python is not **python3**
- `prompt` has to be `FALSE`

**Comment by prokopyev** [comment]
@amatsuo thanks. I've tried 

```# trying to install python in a virtual env
spacy_install_virtualenv(python_path = "/root/.virtualenvs/r-tensorflow/bin/python", prompt = FALSE)``` and got

```
Error: spacyr does not support virtual environment installation for python 2.*
Traceback:

1. spacy_install_virtualenv(python_path = "/root/.virtualenvs/r-tensorflow/bin/python", 
 .     prompt = FALSE)
2. process_spacy_installation_virtualenv(python, virtualenv, version, 
 .     lang_models, prompt)
3. stop("spacyr does not support virtual environment installation for python 2.*", 
 .     call. = FALSE)
```

Interestingly, `reticulate::conda_install()` also yields

```
Error: Unable to find conda binary. Is Anaconda installed?
Traceback:

1. reticulate::conda_binary()
2. stop("Unable to find conda binary. Is Anaconda installed?", call. = FALSE)
```

**Comment by amatsuo** [comment]
So, obviously, there are no conda at Kaggle. What about python3? If it's available and you can find the path to it, then the creation of virtualenv with python3 shouldn't be difficult.

**Comment by amatsuo** [comment]
I myself don't use `spacyr` in Kaggle, but if more people try to do so and fail, I would try doing it by myself and provide some instructions.
