### ISSUE TITLE
Make arbitrary spaCy tokens attributes available via spacy_parse()

### ISSUE THREAD

**Issue by amatsuo** [quanteda/spacyr#139]
Relating to #116.

We could quickly add a new feature in `spacy_parse()` to allow users to extract the value of arbitrary token attributes as additional fields in the output data.frame from `spacy_parse()`.

The full list of attributes are available here: https://spacy.io/api/token#attributes

How I foresee this works is something like
```r
spacy_parse(txt, additional_attributes = c("sentiment", "is_alpha")) 
```
then the output object will have `sentiment` and `is_alpha` fields.

@kbenoit, do you think it's worth implement?

**Comment by kbenoit** [comment]
Yes I do, great idea. 

For error checking, we should either maintain a list of supported attributes and checked the user-supplied values against those, or check them spaCy-side for legal values and filter back to R an appropriate error message.
