### ISSUE TITLE
issue installing with custom paths for model and python

### ISSUE THREAD

**Issue by randomgambit** [quanteda/spacyr#145]
Hello there,

I have an installation issue that I was not able to solve by looking at the previous questions.

For some reason, I have anaconda python 3 installed in some network drive `/mydrive/anaconda/bin` and the custom model for spacy installed in another drive `/otherdrive/model/en_core_web_lg/en_core_web_lg-2.0.0`

when I run `spacy_initialize` with `model=` and `python_executable=` pointing at the two paths above, I get the error:

```
Found 'spacy_condaenv'. spacyr will use this environment
Error in py_run_file_impl(file, local, convert) : 
  ModuleNotFoundError: No module named 'spacy'
```
The package is necessarily installed because I was able to `import spacy` when running `spyder`. What can be the error here? I am using linux.

Thanks!

**Comment by randomgambit** [comment]
I was able to change the paths a little bit, but now when I specify the model path I get

```
> spacy_initialize(model = '/otherdrive/model/en_core_web_lg-2.0.0/en_core_web_lg/en_core_web_lg-2.0.0', 
+                  python_executable = "/mydrive/anaconda/bin/python")
Error in py_run_file_impl(file, local, convert) : 
  ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /mydrive/anaconda/lib/python3.6/site-packages/spacy/gold.cpython-36m-x86_64-linux-gnu.so)
```

What does that mean? Loading the model would work in windows. Any help greatly appreciated here.
Thanks!

**Comment by randomgambit** [comment]
OK, found some clues on the internet. Now it only remains one issue: when I give the path to the model

```
spacy_initialize(model = '/otherdrive/model/en_core_web_lg-2.0.0/en_core_web_lg/en_core_web_lg-2.0.0', 
+                  python_executable = "/mydrive/anaconda/bin/python")

```
I get 
```

Error in py_run_file_impl(file, local, convert) : 
  ImportError: [E048] Can't import language en from spacy.lang.
```

However I was able to load the model from `spyder` directly. Can't we use a path for the model in `spacy_initialize`? This is vital for me as I need to load the model separately (my firewall does not allow the download from conda) @kbenoit please let me know if you have any ideas... I am so close to resolving this and I really need spacy! 

Thanks!!!

**Comment by randomgambit** [comment]
@amatsuo thanks. everything works fine except for the last line. which gives the same error `ImportError: [E048] Can't import language en from spacy.lang.`

Weirdly, loading the model from `spyder` works. I wonder if this is an issue with missing escapes in the string or something between R and Python?

```
Python 3.6.6 |Anaconda custom (64-bit)| (default, Jun 28 2018, 17:14:51)
Type "copyright", "credits" or "license" for more information.

IPython 6.5.0 -- An enhanced Interactive Python.

import spacy

nlp = spacy.load('/otherdrive/model/en_core_web_lg-2.0.0/en_core_web_lg/en_core_web_lg-2.0.0')


doc = nlp(u'Apple is looking at buying U.K. startup for $1 billion')

for token in doc:
    print(token.text, token.lemma_, token.pos_, token.tag_, token.dep_,
          token.shape_, token.is_alpha, token.is_stop)


Apple apple PROPN NNP nsubj Xxxxx True False
is be VERB VBZ aux xx True False
looking look VERB VBG ROOT xxxx True False
at at ADP IN prep xx True False
buying buy VERB VBG pcomp xxxx True False
U.K. u.k. PROPN NNP compound X.X. False False
startup startup NOUN NN dobj xxxx True False
for for ADP IN prep xxx True False
$ $ SYM $ quantmod $ False False
1 1 NUM CD compound d False False
billion billion NUM CD pobj xxxx True False

```

**Comment by amatsuo** [comment]
I suspect that you are using a different python than the one you use from spyder.

```
import sys
print(sys.executable)
```
Does this returns the same for both `spyder` and `reticulate`?

**Comment by randomgambit** [comment]
@amatsuo unfortunately they are the same 

```
    import sys
print(sys.executable)
/mydrive/anaconda/bin/python
```
and in Rstudio

```
py_run_string("import sys")
py_run_string("mycheck = sys.executable")


> py$mycheck
[1] "/mydrive/anaconda/bin/python"

```
Spyder is run in a linux environment while R is run (on windows!!) on a navigator-based version of Rstudio (which access the files available in the Linux network so I guess it is a linux environment). What can be the issue?!

**Comment by amatsuo** [comment]
Hmm. That's a complicated setup. I am a bit of out of idea. Since the code cannot be run from `reticulate`, I can't think of a solution. As a last resort, I'd try creating a conda environemnt and place the model directly under the environment. Not sure it would work though.

**Comment by randomgambit** [comment]
@amatsuo must be some library path issue... dont you think?
