### ISSUE TITLE
Issues installing spacyr on Windows10

### ISSUE THREAD

**Issue by InazeaAnazasi** [quanteda/spacyr#155]
I get the following error when compiling `spacy_install()`:
```Error: Error 1 occurred while checking for python architecture
In addition: Warning message:
running command '"C:\Users\[username]\AppData\Local\Enthought\Canopy\User/python.exe" -c "import sys; import platform; sys.stdout.write(platform.architecture()[0])"' had status 1 
```
I am not at all accostumed with Python, but tried to follow the instructions: I have installed Visual Studio 2017 and Anaconda. I think the error lies with one of those; when I try to install spacy using pip (following the instructions [`here`](https://spacy.io/usage/#source-windows) using `conda install -c conda-forge spacy`, console can't find conda...

**Comment by amatsuo** [comment]
Probably the issue is related to this:
https://stackoverflow.com/questions/44515769/conda-is-not-recognized-as-internal-or-external-command

You need to set an environmental path to conda. Once it's set `spacyr::spacy_install()` would also work.

**Comment by InazeaAnazasi** [comment]
Yes - I can check my Conda-Version in Anaconda Prompt. Thanks for this.

However, what do you mean by setting an environmental path to conda?

**Comment by amatsuo** [comment]
From the [link](https://stackoverflow.com/questions/44515769/conda-is-not-recognized-as-internal-or-external-command) above, you can follow the step suggested by "Raja Rama Mohan Thavalam" to add the path manually.

However,  probably an easier way is to re-install Anaconda and select **Add Anaconda to my PATH...** when prompted (as an answer by "Michael James Kali Galarnyk").

**Comment by amatsuo** [comment]
It seems that the error is coming from `reticulate` package. I am not sure why this is happening but you might try setting up a conda environment manually and check if you can access to the env from R through `reticulate`. 

On the console, create a new env by entering:
```
conda create --name testenv python=3.6
```

Then in R
```{R}
library(reticulate)
use_condaenv("testenv")
py_run_string("print(1)")
```
Do you get any error while executing the code above? If you do, I'd recommend posting the issue on the reticulate page.
