### ISSUE TITLE
condaenv parameter does not work properly when default "spacy_condaenv" is present

### ISSUE THREAD

**Issue by ibombonato** [quanteda/spacyr#157]
I am trying to initialize spacy in another env, not the default one, but it always point to "spacy_condaenv" even when I pass another one.

```
spacy_initialize(model = "pt", condaenv = "spacy_br", refresh_settings = TRUE, entity = TRUE)
> Found 'spacy_condaenv'. spacyr will use this environment
```

After I remove the "spacy_condaenv" from conda it started properly

```
spacy_initialize(model = "pt", condaenv = "spacy_br", refresh_settings = TRUE, entity = TRUE)
> successfully initialized (spaCy Version: 2.0.18, language model: pt)
(python options: type = "condaenv", value = "spacy_br")
```

**Comment by amatsuo** [comment]
Thanks for the report. It seems that you are quite right! The order of checking options in `spacy_initialize()` is causing the issue. I changed the order in a branch `issue-157`. In my test, it seems to be working as it is supposed to be. Could you check?

To install from the branch:
```r
devtools::install_github("quanteda/spacyr", ref = "issue-157")
```

**Comment by kbenoit** [comment]
Thanks @amatsuo and @ibombonato for the alert. Once we verify this solves the issue let's get this into the master and consider a CRAN update.
