### ISSUE TITLE
spacy_initialize() error

### ISSUE THREAD

**Issue by Jared-Caraan** [quanteda/spacyr#162]
I am following the steps provided on how to install and initialize spaCy package in RStudio. Everything was going smoothly until ‘spacy_initialize()’ which shows an error stating that it can’t find model ‘en’. I was confused because when I executed ‘spacy_install()’ earlier, it said that ‘Language model ‘en’ is successfully installed’. How can I resolve this?
Here is the error:
`Error in py_run_file_impl(file, local, convert) : 
  OSError: [E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.`

**Comment by amatsuo** [comment]
Could you try `spacy_initialize(refresh_settings = TRUE)`? 

Also, provide `sessionInfo()`.

**Comment by CivilEngineerUK** [comment]
@amatsuo I have the same issue as @Jared-Caraan. I have tried your suggestion and get the same error, I am sure that the en language pack downloaded during the spacy installation:

```
Found 'spacy_condaenv'. spacyr will use this environment
Error in py_run_file_impl(file, local, convert) : 
  OSError: [E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.
```

  My session info is:

```
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_3.5.1    Matrix_1.2-15     tools_3.5.1       yaml_2.2.0        Rcpp_1.0.1       
 [6] reticulate_1.11.1 grid_3.5.1        data.table_1.12.0 jsonlite_1.6      spacyr_1.0       
[11] lattice_0.20-38  
```

Any help is appreciated. Thanks

**Comment by amatsuo** [comment]
I would try running spacy from conda environment. Could you enter the following line-by-line?

Firstly activate the conda environment and log in the python:
```
activate spacy_condaenv
python
```

Then type the following:
```
import spacy
nlp = spacy.load("en")
```
If the last line raises an error, the linking to the model has failed in `spacy_install()`.

**Comment by Jared-Caraan** [comment]
@amatsuo I have tried on the conda environment and indeed it is having an error on the last line like this:
`>>> import spacy
>>> nlp = spacy.load("en")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\jcaraan\AppData\Local\Continuum\anaconda3\envs\spacy_condaenv\lib\site-packages\spacy\__init__.py", line 27, in load
    return util.load_model(name, **overrides)
  File "C:\Users\jcaraan\AppData\Local\Continuum\anaconda3\envs\spacy_condaenv\lib\site-packages\spacy\util.py", line 136, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.
>>>`

**Comment by amatsuo** [comment]
Then the problem is the installation failure, and most likely it was because R was not run as admin when `spacy_install()` was called. 

For details, see **3.** of this link: https://spacyr.quanteda.io/#installing-the-package

**Comment by Jared-Caraan** [comment]
I think I've resolved it by using `spacy_initialize(model = 'en_core_web_sm')`. I can now execute and see my array of words and their corresponding part of speeches. 
Try it @CivilEngineerUK. 
Thank you very much @amatsuo !

**Comment by amatsuo** [comment]
Ya. That should work. The reason why we recommend running R as admin is to exactly because of that. 

To call a model with `model = "en"`, spaCy has to create a symlink to "en_core_web_sm". I don't know why, but WindowsOS seems not allow non-admin users to create symlinks.
