### ISSUE TITLE
how to feed a tibble to spacyr?

### ISSUE THREAD

**Issue by randomgambit** [quanteda/spacyr#164]
Hello the dream-quanteda team!

Could you please have a look at my SO question here? https://stackoverflow.com/questions/55518184/how-to-feed-a-tibble-to-spacyr 

I believe this is a very common situation. I am not sure how can we fix that issue and get some decent performance.

Thanks!

**Comment by amatsuo** [comment]
I answered on the stackoverflow. The bug is already fixed in the github version, but still exists on the cran version. Thanks for the report!

**Comment by randomgambit** [comment]
@amatsuo actually I download the master from github, and I get the same error. Should I download another version?

**Comment by amatsuo** [comment]
hmm, that's weird. I tried a fresh install and it worked... I did the following:

```r
devtools::install_github("quanteda/spacyr")
library(spacyr)

spacy_uninstall()
spacy_install()

spacy_parse('838383838', lemma = FALSE, entity = TRUE, nounphrase = TRUE)
```
Tha last line provides:
```
## Found 'spacy_condaenv'. spacyr will use this environment
## successfully initialized (spaCy Version: 2.1.3, language model: en)
## (python options: type = "condaenv", value = "spacy_condaenv")
## No noun phrase found in documents.
## doc_id sentence_id token_id     token pos     entity
## 1  text1           1        1 838383838 NUM CARDINAL_B
```

**Comment by randomgambit** [comment]
@amatsuo the issue is that I cannot use `install_github` because of the firewall. I am downloading the `spacy-master` zip from github. Is that the right one? there are other branches.

I also get a successful initialization.  
```

> spacy_initialize(python_executable = 'C:\\Users\\john\\AppData\\Local\\Continuum\\anaconda3\\python.exe',
+                  model = 'W://resources/en_core_web_lg-2.1.0/en_core_web_lg/en_core_web_lg-2.1.0')
successfully initialized (spaCy Version: 2.1.3, language model: W://resources/en_core_web_lg-2.1.0/en_core_web_lg/en_core_web_lg-2.1.0)
```

but still the same error
```

> spacy_parse('838383838', lemma = FALSE, entity = TRUE, nounphrase = TRUE)
Error in `$<-.data.frame`(`*tmp*`, "doc_id", value = "text1") : 
  replacement has 1 row, data has 0
```

**Comment by amatsuo** [comment]
Try `packageVersion("spacyr")`. If the version is `1.1`, then that should be correct.

**Comment by randomgambit** [comment]
nope its `1.0`... how can I get the good one manually? thanks!!

**Comment by amatsuo** [comment]
The link should be `https://github.com/quanteda/spacyr/archive/master.zip`. 

Once unzip the downloaded file, `cd` to the unziped package directory, then:
```r
devtools::install(".", upgrade = 'never')
```
In my environment, it worked...

**Comment by randomgambit** [comment]
that is so weird. I downloaded the zip, and then used the install from zip in `Rstudio` and still somehow I get the version `1.0`

```
> install.packages("W:/resources/spacyr-master.zip", repos = NULL, type = "win.binary")
Installing package into ‘C:/Users/john/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
> packageVersion("spacyr")
[1] ‘1.0’
```

**Comment by randomgambit** [comment]
I installed `R 3.5` to make sure. it seems something is wrong with the package (renamed `spacyr` from `spacyr-master`)

```
> install.packages("W:/resources/spacyr.zip", repos = NULL, type = "win.binary")
Installing package into ‘C:/Users/john/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
Warning in install.packages :
  cannot open compressed file 'spacyr/DESCRIPTION', probable reason 'No such file or directory'
Error in install.packages : cannot open the connection
```

**Comment by randomgambit** [comment]
solved using devtools and installing the new rtools
