### ISSUE TITLE
multiprocessing still a bit slow

### ISSUE THREAD

**Issue by randomgambit** [quanteda/spacyr#165]
Hello there,

I am trying to run `spacy_parse()` on a large tibble (about 300k rows) with the `multithread = TRUE` option and despite my 20 cores I do no see a lot of CPU usage in the task manager. The processing is very slow. 

Is there an expected bottleneck when `R` wraps `spacyr`? Were you able to get sizeable processing time gains with the `multithread` argument?

Thanks!

**Comment by randomgambit** [comment]
Ha! actually after running for an hour, I get the error
`
 Error in py_run_string_impl(code, local, convert) : AssertionError: `

Running the program on a small sample of the tibble works without issues. Do you know what is going on here?

**Comment by randomgambit** [comment]
i can confirm the processing works without the `multithread` argument (but is impractically slow)

**Comment by randomgambit** [comment]
related https://github.com/explosion/spaCy/issues/3556

**Comment by amatsuo** [comment]
I am not sure why this is happening. Probably I will wait for spaCy guys to sort out. I might try other implementation of multithreading if I could find the time.

**Comment by amatsuo** [comment]
This is resolved here:
https://github.com/explosion/spaCy/issues/3556

The issue was Windows implementation of some of python packages (`spaCy` or `joblib`)
