### ISSUE TITLE
Calling full model name by default

### ISSUE THREAD

**Issue by amatsuo** [quanteda/spacyr#177]
At the moment, `spacy_initialize` use the default model name `en`. This would become a bit confusing as we are planning to use word-vectors that come with spaCy language models and vectors come only with `_lg` or `_md` (#171). Once this is implemented, we expect a number of `spacyr` users will have multiple models from the same language. 

I think we should use a full model name as the default (e.g. the default will be `en_core_web_sm`) to avoid this confusion. 

That's also what @ines recommends:
https://support.prodi.gy/t/spacy-load-en-download/1858

This will be implemented with #171 (unless vetoed by @kbenoit or someone else).

**Comment by kbenoit** [comment]
I agree, let's implement this in the next update. But as a transitional step, we should map the two-character language names to the "default" language models, if those exist, and print a warning.

**Comment by kbenoit** [comment]
Now in `master`.
