### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by CCristancho** [quanteda/spacyr#178]
I'm trying to reinstall spacyr after updating to R 3.6.1 and cleaning windows trash but I have problems even after reinstalling a new Miniconda3 and Visual studio community 2019. I have the latest spacyr version from devtools::install_github("quanteda/spacyr", build_vignettes = FALSE).

When trying to spacy_install() I get "Error: Conda installation failed (no conda binary found)". If I provide the route to conda.exe it works for installing spacy: 
spacy_install(conda = "C:/Users/camil/Miniconda3/_conda.exe", version = "latest", lang_models = "en", python_version = "3.7", envname = "spacy_condaenv", pip = FALSE, prompt = TRUE)

But then I get "Error: Error 127 occurred installing packages into conda environment spacy_condaenv" when it gets to installing model "en". I get the same error if I do: spacy_download_langmodel(model = "en_core_news_sm", envname = "spacy_condaenv",conda = "C:/Users/camil/Miniconda3/_conda.exe").

Is there something I'm getting wrong in my Windows configuration? Thanks!

**Comment by amatsuo** [comment]
I suspect the error is related to the admin privilege. 

As in README:

- For Windows, you need to run R as an administrator to make installation work properly. To do so, right click the RStudio icon (or R desktop icon) and select “Run as administrator” when launching R.

**Comment by CCristancho** [comment]
Thanks @amatsuo. I did use admin privilege before. I'm now trying to establish why it doesn't find a python executable with spaCy installed. 

I tried reticulate::py_versions_windows() and get this:
        type hive               install_path                        executable_path version arch
1 PythonCore  HCU C:\\Users\\camil\\MINICO~1 C:\\Users\\camil\\MINICO~1\\python.exe     3.7  x64
2   Anaconda  HCU C:\\Users\\camil\\MINICO~1 C:\\Users\\camil\\MINICO~1\\python.exe     3.7  x64

But when I try spacy_initialize(conda = "C:/Users/camil/Miniconda3/_conda.exe") I get:
"spacy python option is already set, spacyr will use:
	condaenv = "C:/Users/camil/Miniconda3/_conda.exe"
Error: Unable to find conda binary. Is Anaconda installed?"

The same occurs with spacy_download_langmodel(). That's why I suspect it is a Windows problem on the paths...

**Comment by amatsuo** [comment]
There are several things you can try:

1. Refresh spacyr setting by running `spacy_initialize(refresh_settings = T)`
2. Check if reticulate works properly. Restart R and try something like:
    ```R
    library(reticulate)
    conda_create("test_env") 
    use_condaenv("test_env")
    os <- import("os")
    ```

**Comment by CCristancho** [comment]
Thanks @amatsuo! Finally solved. The use_condaenv("test_env") tok me to reticulate::install_miniconda() function and it installed miniconda in the correct path.
Best regards,
