### ISSUE TITLE
spacy_parse() terminates R

### ISSUE THREAD

**Issue by julia-schilling** [quanteda/spacyr#182]
<img width="481" alt="Bildschirmfoto 2020-01-19 um 15 23 00" src="https://user-images.githubusercontent.com/60067428/72682642-96bf9280-3acf-11ea-9c52-a707a17043e3.png">

every time I try to run spacy_parse(), R gets terminated. I am using the newest version of spacy and R on OSX 10.15.

**Comment by hyuninpark** [comment]
The same exact issue is happening to me.  Did anyone have a solution to this?

**Comment by kbenoit** [comment]
Can you please add your `sessionInfo()` output?

Did you try `spacy_uninstall()` then `spacy_install()` again, after updating all of your packages?

**Comment by hyuninpark** [comment]
`> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Catalina 10.15.2

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] spacyr_1.2

loaded via a namespace (and not attached):
[1] compiler_3.6.1    tools_3.6.1       yaml_2.2.1        Rcpp_1.0.3        reticulate_1.14   data.table_1.12.8
[7] jsonlite_1.6.1   `

I updated all the packages and uninstalled and installed, and it still makes R crash. I think it has something to do with the Mac OS, but I am not sure.

**Comment by aquevedo93** [comment]
I am encountering the same issue; spacy_parse() is terminating my R session. I tried  spacy_uninstall() then spacy_install() after re-installing reticulate and it is still crashing. 

> sessionInfo()
R version 3.6.2 (2019-12-12)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Catalina 10.15.3

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.2 tools_3.6.2

**Comment by kbenoit** [comment]
I would love to help, but cannot replicate the problem. I did notice however that my version of spaCy is newer than the 2.0.16 reported by @julia-schilling [above](https://github.com/quanteda/spacyr/issues/182#issue-551929740).

```r
> library("spacyr")
> spacy_initialize()
spacy python option is already set, spacyr will use:
	condaenv = "spacy_condaenv"
successfully initialized (spaCy Version: 2.1.4, language model: en)
(python options: type = "condaenv", value = "spacy_condaenv")
> spacy_parse("I cannot replicate the problem reported.")
  doc_id sentence_id token_id     token     lemma   pos entity
1  text1           1        1         I    -PRON-  PRON       
2  text1           1        2       can       can   AUX       
3  text1           1        3       not       not   ADV       
4  text1           1        4 replicate replicate  VERB       
5  text1           1        5       the       the   DET       
6  text1           1        6   problem   problem  NOUN       
7  text1           1        7  reported    report  VERB       
8  text1           1        8         .         . PUNCT       
> sessionInfo()
R version 3.6.2 (2019-12-12)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Catalina 10.15.3

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] spacyr_1.2

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3         rstudioapi_0.11    magrittr_1.5       usethis_1.5.1.9000
 [5] devtools_2.2.2     pkgload_1.0.2      R6_2.4.1           rlang_0.4.4       
 [9] fansi_0.4.1        httr_1.4.1         tools_3.6.2        pkgbuild_1.0.6    
[13] data.table_1.12.8  sessioninfo_1.1.1  cli_2.0.1          git2r_0.26.1      
[17] withr_2.1.2        ellipsis_0.3.0     remotes_2.1.1      assertthat_0.2.1  
[21] digest_0.6.24      rprojroot_1.3-2    crayon_1.3.4       processx_3.4.2    
[25] callr_3.4.2        clisymbols_1.2.0   fs_1.3.1           ps_1.3.2          
[29] curl_4.3           testthat_2.3.1     memoise_1.1.0      glue_1.3.1        
[33] compiler_3.6.2     desc_1.2.0         backports_1.1.5    prettyunits_1.1.1 
[37] jsonlite_1.6.1     reticulate_1.14 
```

I also just ran `spacy_upgrade()` and it upgraded my spaCy installation to 2.2.3, and upgraded the language model. The crash _might be_ caused by an older language model. I suggest you run `spacy_upgrade()` and try this again. (I can verify that the same code as above also worked after my upgrade.)

**Comment by hyuninpark** [comment]
For some reason whenever I run spacy_upgrade(), the function would say that spacy has been upgraded successfully to 2.2.3, but whenever I run spacy_initialize(), it would use the old version (2.0.16). Also, when I call spacy_upgrade() afterwards, it will say that my version currently 2.0.16, and an update 2.2.3 is found. So basically it seems that the spacy_upgrade() function does not actually upgrade spacy.

**Comment by hyuninpark** [comment]
I managed to update spacy and it works now! I uninstalled and used spacy_install(version='2.2.3'), and everything works well now. Thank you so much!

**Comment by aquevedo93** [comment]
spacy_install(version='2.2.3') worked for me too! Thank you!
