### ISSUE TITLE
How to install and/or initialize language models for French?

### ISSUE THREAD

**Issue by lbocken** [quanteda/spacyr#196]
For English, this works fine :
`  spacyr::spacy_initialize(model = "en_core_web_sm")`

For French, I tried these lines of code without success :
`spacyr::spacy_initialize(model = "fr_core_web_sm")`
 `spacyr::spacy_initialize(model = "fr_core_news_md")`
 `spacyr::spacy_initialize(model = "fr_core_news_lg")`
 `spacyr::spacy_initialize(model = "fr")`

I had always the same error message : 
`Error in py_run_file_impl(file, local, convert) : 
  OSError: [E050] Can't find model 'fr_core_news_md'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.`

Thank you very much for your help !

**Comment by kbenoit** [comment]
The language model names have changed in spaCy, see https://spacy.io/models/fr.

This will work:

```r
library("spacyr")
spacy_download_langmodel("fr_core_news_sm")
spacy_initialize(model = "fr_core_news_sm")
```

**Comment by lbocken** [comment]
*Sorry to bother you again...*

*Here is what I had for English :*
> library("spacyr")
> spacy_download_langmodel("en_core_web_sm")
Installing model "en_core_web_sm"


C:\Users\Ludovic\Documents>conda.bat activate spacy_condaenv
Could not find conda environment: spacy_condaenv
You can list all discoverable environments with `conda info --envs`.

Erreur : Error 1 occurred installing packages into conda environment
spacy_condaenv
> spacy_initialize(model = "en_core_web_sm")
Python space is already attached.  If you want to switch to a different
Python, please restart R.
successfully initialized (spaCy Version: 2.2.3, language model:
en_core_web_sm)
(python options: type = "condaenv", value = "spacy_condaenv")

*and for French :*
> library("spacyr")
> spacy_download_langmodel("fr_core_news_sm")
Installing model "fr_core_news_sm"


C:\Users\Ludovic\Documents>conda.bat activate spacy_condaenv
Could not find conda environment: spacy_condaenv
You can list all discoverable environments with `conda info --envs`.

Erreur : Error 1 occurred installing packages into conda environment
spacy_condaenv
> spacy_initialize(model = "fr_core_news_sm")
spaCy is already initialized
NULL

Thank you very much for your help !

Ludovic BOCKEN
lbocken@gmail.com
www.ludovicbocken.com
Skype: ludovic.bocken
http://www.linkedin.com/in/ludovicbocken
2222 Rue Hochelaga,
Montréal, QC H2K 4N8
+1 (514) 649 0755

*Avis de confidentialité*

Le présent message transmis par télécopie est confidentiel, et son contenu
peut être protégé par le secret professionnel. Il est à l’usage exclusif de
son ou sa destinataire. Toute autre personne est par les présentes avisée
qu’il lui est strictement interdit de le diffuser, de le distribuer ou de
le reproduire. Si la ou le destinataire ne peut être joint ou vous est
inconnu, nous vous prions d’en informer immédiatement l’expéditeur ou
l’expéditrice et de détruire ce message et toute copie de celui-ci.



Le jeu. 30 juil. 2020 à 07:42, Kenneth Benoit <notifications@github.com> a
écrit :

**Comment by kbenoit** [comment]
It's hard to diagnose your issue without knowing exact version information, but if you restart your R sessions, then this set of steps should work:

``` r
library("spacyr")
packageVersion("spacyr")
## [1] '1.2.1'

spacy_upgrade()
## checking spaCy version
## Your spaCy version is the latest available.
spacy_download_langmodel("fr_core_news_sm")
## Installing model "fr_core_news_sm"
## Language model "fr_core_news_sm" is successfully installed
spacy_initialize(model = "fr_core_news_sm")
## Found 'spacy_condaenv'. spacyr will use this environment
## successfully initialized (spaCy Version: 2.3.2, language model: fr_core_news_sm)
## (python options: type = "condaenv", value = "spacy_condaenv")
```
You will not need to repeat the `spacy_upgrade()` or the `spacy_download_langmodel()` steps until there is some change in the underlying spaCy library (the Python library on which **spacyr** is built).

**Comment by lbocken** [comment]
*Here is what I had : *

> library("spacyr")
Warning message:
le package ‘spacyr’ a été compilé avec la version R 3.6.3
> packageVersion("spacyr")
[1] ‘1.2.1’
> spacy_upgrade()
checking spaCy version
Error in system2(cmd1, cmd2, stdout = TRUE, stderr = TRUE) :
  '"\"C:/Users/Ludovic/AppData/Local/r-miniconda/condabin/activate\""' not
found
De plus : Warning message:
In system(cmd, intern = TRUE, ignore.stderr = TRUE) :
  l'exécution de la commande
'"C:/Users/Ludovic/AppData/Local/r-miniconda/condabin/activate"
spacy_condaenv && pip search spacy' renvoie un statut 1
> ## checking spaCy version
> ## Your spaCy version is the latest available.
> spacy_download_langmodel("fr_core_news_sm")
Installing model "fr_core_news_sm"


C:\Users\Ludovic\Documents>conda.bat activate spacy_condaenv
Could not find conda environment: spacy_condaenv
You can list all discoverable environments with `conda info --envs`.

Erreur : Error 1 occurred installing packages into conda environment
spacy_condaenv
> ## Installing model "fr_core_news_sm"
> ## Language model "fr_core_news_sm" is successfully installed
> spacy_initialize(model = "fr_core_news_sm")
Found 'spacy_condaenv'. spacyr will use this environment
Error in py_run_file_impl(file, local, convert) :
  OSError: [E050] Can't find model 'fr_core_news_sm'. It doesn't seem to be
a shortcut link, a Python package or a valid path to a data directory.


*Thank you very much for your help !*

Ludovic BOCKEN
lbocken@gmail.com
www.ludovicbocken.com
Skype: ludovic.bocken
http://www.linkedin.com/in/ludovicbocken
2222 Rue Hochelaga,
Montréal, QC H2K 4N8
+1 (514) 649 0755

*Avis de confidentialité*

Le présent message transmis par télécopie est confidentiel, et son contenu
peut être protégé par le secret professionnel. Il est à l’usage exclusif de
son ou sa destinataire. Toute autre personne est par les présentes avisée
qu’il lui est strictement interdit de le diffuser, de le distribuer ou de
le reproduire. Si la ou le destinataire ne peut être joint ou vous est
inconnu, nous vous prions d’en informer immédiatement l’expéditeur ou
l’expéditrice et de détruire ce message et toute copie de celui-ci.



Le jeu. 30 juil. 2020 à 10:43, Kenneth Benoit <notifications@github.com> a
écrit :

**Comment by lbocken** [comment]
I don't understand the situation. Here is the content of the directory :
`C:\Users\Ludovic\AppData\Local\r-miniconda\condabin

23/04/2020  10:23    <DIR>          .
23/04/2020  10:23    <DIR>          ..
13/03/2020  13:03               147 activate.bat
13/03/2020  13:03             1 415 conda.bat
13/03/2020  13:03               530 conda_auto_activate.bat
13/03/2020  13:03               649 conda_hook.bat
13/03/2020  13:03               192 deactivate.bat
13/03/2020  13:03                65 rename_tmp.bat
13/03/2020  13:03             2 585 _conda_activate.bat
               7 fichier(s)            5 583 octets
               2 Rép(s)  71 023 742 976 octets libres
`


Thank you very much for your help to better understand the problem !
