### ISSUE TITLE
Loading custom spacy NER model into Spacyr

### ISSUE THREAD

**Issue by mshariful** [quanteda/spacyr#198]
Hello,

I have sucessfully updated Spacy NER model (using Python / Spyder IDE)  with own data and the model is saved in a folder
called 'c:\updated_ner'. I can easily load this updated model from Python/ Spyder IDE by simple command

```
import spacy
nlp=spacy.load('c:\updated_ner')
```

and then everything works fine. How do I use my updated NER model in Spacyr? I have  got
a script from a person where he uses

`parsed_text<-spacyr::spacy_parse(x = text, lemma = TRUE, entity = TRUE)`

How do I make sure that spacyr use my updated NER model? My python (Anaconda distribution) (that's used to update the Spacy NER model) is different  from my spacyr's python that got installed in RStudio
as I used spacy_install() command from Spacyr.

Thank you very much for your support.

Regards,
Sharif

**Comment by kbenoit** [comment]
Same as #180, closing here.
