### ISSUE TITLE
multithreaded for pos tagging only supported?

### ISSUE THREAD

**Issue by KnutJaegersberg** [quanteda/spacyr#199]
Hi,
I try to use multithreaded option for parallel pos tagging (or are only other parts supported for multiprocessing), but it stays one proces, on two different pcs. In both cases I updated to most recent spacy and spacyr versions. using udpipe for parallel pos tagging, but I guess spacy is way more efficient on this?
Is it something likely in both of my linux environments or is parallel pos tagging not supported?

**Comment by kbenoit** [comment]
Hi @KnutJaegersberg - It's single-threaded in R but should be multi-threaded in the Python backend. But maybe @amatsuo knows more about this?

**Comment by kbenoit** [comment]
We will make multi-threading more flexible and robust, moving to #185.
