### ISSUE TITLE
spacy_initialize() shows NULL

### ISSUE THREAD

**Issue by fcobolanos** [quanteda/spacyr#203]
I am trying to install spacyr in Windows 10, but when I run spacy_initialize() it shows NULL. This is the what I did:
![PipInstallation](https://user-images.githubusercontent.com/49967266/103344092-99569600-4a5b-11eb-8c4b-ac990df2fc05.JPG)
![spacy_install01](https://user-images.githubusercontent.com/49967266/103344095-99ef2c80-4a5b-11eb-8903-78bd4c7cbf88.JPG)
![spacy_install02](https://user-images.githubusercontent.com/49967266/103344097-9a87c300-4a5b-11eb-977a-5030ca41ab8c.JPG)
![sessionInfo](https://user-images.githubusercontent.com/49967266/103344114-9eb3e080-4a5b-11eb-9e47-ca303b14544e.JPG)

I really appreciate your feedback!!!

**Comment by kbenoit** [comment]
Not sure what's happening here. You could try it with the "virtualenv" rather than the default "conda". 

@amatsuo might have some ideas too.
