### ISSUE TITLE
Sparklyr doesn´t  work

### ISSUE THREAD

**Issue by fcobolanos** [quanteda/spacyr#208]
I am new to Sparklyr, I am trying to load it, but I get the following error

![error](https://user-images.githubusercontent.com/49967266/124234921-462cd100-dada-11eb-84ed-ca4ca4b3f871.PNG)

I read that this could be of the missing winutils.exe file , but I don´t understand what exactly I have to do.

Thank you  for your advice

**Comment by kbenoit** [comment]
I think you have the wrong issues page - you want https://github.com/sparklyr/sparklyr/issues.
