### ISSUE TITLE
Error in py_run_file_impl(file, local, convert) :    ModuleNotFoundError: No module named 'spacy'

### ISSUE THREAD

**Issue by Siobhanmcc** [quanteda/spacyr#211]
Hi there, 
I have installed spacyr but when I go to run spacy_initialize() I get the following message. 

Found 'spacy_condaenv'. spacyr will use this environment
Error in py_run_file_impl(file, local, convert) : 
  ModuleNotFoundError: No module named 'spacy'
In addition: Warning message:
Python '/opt/anaconda3/envs/spacy_condaenv/bin/python' was requested but '/Users/siobhanmccauley/.local/share/virtualenvs/siobhanmccauley-1aJAMhYc/bin/python' was loaded instead (see reticulate::py_config() for more information) 

Any ideas what I can do?

**Comment by MarcinKosinski** [comment]
@Siobhanmcc did you try running reticulate::py_config() ?
Is it still valid issue or can we close?

**Comment by kbenoit** [comment]
Closing but if you are still having trouble, add a note.
