### ISSUE TITLE
Convert tokens with POS tag from US to UK English

### ISSUE THREAD

**Issue by seb-29** [quanteda/spacyr#212]
Hello! I parsed my corpus with spacyr and then extracted the tokens with their respective POS tag (e.g. "neighbor/NOUN"). Is there a way I can now convert the spelling of these tokens from American to British English? Thanks a lot in advance!

**Comment by kbenoit** [comment]
Not in **spacyr** but see `?quanteda.dictionaries::data_dictionary_us2uk`. 

https://github.com/kbenoit/quanteda.dictionaries
