### ISSUE TITLE
Typo in the documentation

### ISSUE THREAD

**Issue by MarcinKosinski** [quanteda/spacyr#216]
Should thie line https://github.com/quanteda/spacyr/blob/master/R/spacy_initialize.R#L16

````
#'   installed Example: \code{condalenv = "myenv"}
````
has an extra `l` that should be removed so it's

````
#'   installed Example: \code{condaenv = "myenv"}
````

**Comment by kbenoit** [comment]
Thanks @MarcinKosinski

**Comment by MarcinKosinski** [comment]
@kbenoit did you also build manual pages? I still see this typo in .Rd https://github.com/quanteda/spacyr/blob/master/man/spacy_initialize.Rd#L30
I didn't run the build and didn't fix the typo on my own, as I am not sure I have all the needed dependencies to run your builds

**Comment by kbenoit** [comment]
yes done now
