### ISSUE TITLE
Installing language models - "sv_core_news_lg" won't work

### ISSUE THREAD

**Issue by andersolarsson** [quanteda/spacyr#219]
Hello,

First of all, thank you for your excellent work with spacyr. I hope you can assist me here - I am having issues installing Swedish language models - running `spacy_download_langmodel("sv_core_news_lg")` gives me the following:

```
Installing model "sv_core_news_lg"
✘ No compatible package found for 'sv_core_news_lg' (spaCy v3.1.3)
 Error: Error 1 occurred installing packages into conda environment spacy_condaenv
```

What puzzles me is that I can install Danish (`da_core_news_trf`), Norwegian (`nb_core_news_lg`) and French (`fr_dep_news_trf`) language models just fine but the Swedish model does not want to download. I also tried `sv_core_news_sm` with the same results. I would be thankful for any assistance you can provide me with.

Best,
Anders

**Comment by kbenoit** [comment]
This is probably because the language models are kept up to date from the spaCy server, but your spaCy version was not current. You can either uninstall and reinstall it through **spacyr**, or try `spacy_upgrade()`.

I just verified the this works for spaCy 3.4:

```r
> spacy_download_langmodel("sv_core_news_lg")
Installing model "sv_core_news_lg"
...
Installing collected packages: sv-core-news-lg
Successfully installed sv-core-news-lg-3.4.0
✔ Download and installation successful
You can now load the package via spacy.load('sv_core_news_lg')
Language model "sv_core_news_lg" is successfully installed
```
