### ISSUE TITLE
spacyr_parsed objects & data read-in

### ISSUE THREAD

**Issue by TimBMK** [quanteda/spacyr#232]
I'm currently using spacyr to work with large amounts of textual data (thanks for this great package, btw!). Since I prefer using functions like vroom over RDS to save and read-in larger amounts of data, I ran into a problem with the spacyr_parsed format. Apparently, and contrary to what the documentation of spacy_parse() states, spacy_parse() output is not a data.frame, but seems to be a sepcific spacyr_parsed format. This means that, when saving and reading in the parsed data with e.g. vroom (as .csv), functions like entitiy_extract() fail with:

`Error in UseMethod("entity_extract") : 
  no applicable method for 'entity_extract' applied to an object of class "c('tbl_df', 'tbl', 'data.frame')"`

This error is easily reproducible when any spacy_parse() output is converted to a data.frame before applying entity_extract(), e.g.

`parsed_text %>% as.data.frame() %>% entity_extract()`

Is there a way to convert data.frames back into a proper spacyr_parsed object? Especially with large data, this would be tremendously helpful for the read-in of data. 

Furthermore, I think the documentation of spacy_parse() should state more clearly that its output is not merely a data.frame, since functions like entity_extract() refer to the documentation of spacy_parse() for their expected data input.

**Comment by amatsuo** [comment]
You need to do two things to do what you need (in the `tidyverse` framework). 

1. Assign class `spacyr_parsed`
2. Replace NA with black char string

Here is an example code.

```{r}
library(spacyr)
library(tidyverse)

spacy_initialize()
parsed <- quanteda::data_char_sampletext %>% spacy_parse()

tmp_file <- tempfile(fileext = ".csv")

parsed %>% vroom::vroom_write(file = tmp_file)
parsed_read <- vroom::vroom(tmp_file)

class(parsed_read) <- c(class(parsed_read), "spacyr_parsed") # adding new class
parsed_read %>% replace_na(replace = list(entity = "")) %>% # replace NA 
  entity_consolidate()
```

**Comment by amatsuo** [comment]
No problem! We may think to add some notes for the help file.
