### ISSUE TITLE
spacyr on M1 Max Chip?

### ISSUE THREAD

**Issue by ConchuirohAodha** [quanteda/spacyr#240]
Hi,
I have installed spacyr and miniconda successfully on a MAC with the M1 Max Chip.

However, when I run spacy_initialize()  I am getting a strange error saying 'mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')

Does spacyr run on M1 Max Chips ?

context of error message:
tried: '/Users/cohu/miniconda3/envs/spacy_condaenv/lib/libpython3.9.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))

**Comment by kbenoit** [comment]
I'm running on M1 Max right now and **spacyr** runs perfectly. Your issue appears to be a Python problem, not one related to spacyr. I'd suggest reinstalling.

**Comment by kbenoit** [comment]
See https://github.com/quanteda/quanteda/issues/2230#issuecomment-1495310233

This might be the same problem here.

**Comment by kbenoit** [comment]
Should be resolved with v1.3.
