### ISSUE TITLE
Documention where I can find what are the entities and tags

### ISSUE THREAD

**Issue by scro1991** [quanteda/spacyr#254]
Hi thans for this lovely packages it is really amazing. However, I have a hard time to find a link where I can find exaplanations of what given entities types or tags mean. Am I missing something? Would be good to add a link to such source in package documentation.

**Comment by kbenoit** [comment]
Thanks!

You can find more from `?spacyr::spacy_parse` and look for the hyperlinks under the `pos` and `tag` arguments.
