### ISSUE TITLE
question on parallelisation

### ISSUE THREAD

**Issue by jwijffels** [quanteda/spacyr#93]
Hello,

I'm trying to compare Spacy and UDPipe (https://CRAN.R-project.org/package=udpipe) regarding a number of things namely

1. Easy of use
2. Annotation possibilities
3. Annotation languages
4. Annotation speed
5. Annotation accuracy of the models

Regarding the annotation speed. I'm trying to make a fair comparison.
I see you are  basically using `doc = self.nlp(text)` in https://github.com/quanteda/spacyr/blob/master/inst/python/spacyr_class.py . Does this already do parallel processing in Spacy itself?
Many thanks for the input if you can share details on that.

**Comment by kbenoit** [comment]
Hi @jwijffels - Thanks for the heads up. **udpipe** looks very impressive!

Noting also for comparison purposes, since **spacyr** is just a wrapper around [spaCy](http://spacy.io), its speed is mostly determined by those of the underlying spaCy, and its languages and accuracy entirely so.

One thing you might consider for "fairness" in the comparison is excluding the `spacy_initialize()` step from the comparison, since that adds a fixed overhead of 3-8 seconds depending on your machine and how much searching you make the function do.

@amatsuo is going to reply separately on the parallelization issue.

**Comment by amatsuo** [comment]
Hi @jwijffels - Thanks for the post. I'm quite impressed with the cleanness and diversity of the NLP solution **udpipe** provides. A number of languages it can handle itself is quite amazing. As I am interested in some of the languages in **udpipe** but not in **spaCy**, I can't wait to test it out.

Regarding the parallelization, `spacyr` has not the functionality. I am aware of `spaCy` has the multithreading functionality (e.g. using `pipe()` method). 
https://spacy.io/usage/processing-pipelines#section-multithreading

As I want to improve the speed of `spacy_parse()` (c.f. #90), I have been checking it out as a possible solution for performance enhancement. But at the moment, I am not positive for doing it, as it seems not so straightforward to make it functional even on python. 

They have an example of multithreading included in the github repo:
https://github.com/explosion/spaCy/blob/master/examples/pipeline/multi_processing.py

But, when I tried the example, I faced the issue discussed in this issue:
https://github.com/explosion/spaCy/issues/1669

I am not sure how many people are trying to use multithreading for spaCy and encountered this trouble, but at the moment, trying parallel processing would not be something we can confidently implement for various environments `spacyr` would be installed. 

This is my tentative answer, but I will keep looking for the way to work on it. Also, if you have any idea or suggestions about get multi-threading working, we are very eager to hear.

**Comment by jwijffels** [comment]
@amatsuo thank you for the input. 
I'm just trying to make a comparison on the different tools which are available for R users (spacy, udpipe, corenlp, pattern.nlp, opennlp, ...). One of the elements is accuracy, another one speed. If there is no multithreading involved in the current implementation of spacyr, I know now how to benchmark them. Thanks for the input.

**Comment by jaymon0703** [comment]
Hi @amatsuo just checking in to confirm multithreading is not possible yet from spacyr? Thanks!
